version: "3.8"

services:
  frontend:
    build:
      context: C:/Users/Ricar/OneDrive/Documentos/VS_CODE/GDA/visual
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - C:/Users/Ricar/OneDrive/Documentos/VS_CODE/GDA/visual:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
